name: neurovelo_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - expat=2.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.9.18
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - anndata==0.10.3
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.4
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - fonttools==4.45.0
      - fqdn==1.5.1
      - fsspec==2023.10.0
      - get-annotations==0.1.2
      - h5py==3.10.0
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - iprogress==0.4
      - ipykernel==6.27.0
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.11.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - llvmlite==0.41.1
      - loompy==3.0.7
      - markupsafe==2.1.3
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - natsort==8.4.0
      - nbclient==0.9.0
      - nbconvert==7.11.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - neurovelo==0.0.4
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numba==0.58.1
      - numpy==1.23.0
      - numpy-groupies==0.10.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - overrides==7.4.0
      - packaging==23.2
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - patsy==0.5.3
      - pexpect==4.8.0
      - pillow==10.1.0
      - platformdirs==4.0.0
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygments==2.17.2
      - pynndescent==0.5.11
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.31.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.13.1
      - scanpy==1.9.6
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - scvelo==0.2.5
      - seaborn==0.12.2
      - send2trash==1.8.2
      - session-info==1.0.0
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - statsmodels==0.14.0
      - stdlib-list==0.10.0
      - sympy==1.12
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==2.1.1
      - torchdiffeq==0.2.3
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - triton==2.1.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - umap-learn==0.5.5
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wcwidth==0.2.12
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - widgetsnbextension==4.0.9
      - zipp==3.17.0
